name: 🧪 build

on:
  push:
    branches: *
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get deps
        run: |
          apt-get install cmake ninja clang
          
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -GNinja ..
          ninja

